"""AI-Toolkit — Flux/SD image generation training."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import torch
import torch.nn as nn

from imo.data.dataset_spec import ModelCategory
from imo.toolkits.base import ToolkitCapability, ToolkitInfo, TrainingToolkit


class AIToolkitAdapter(TrainingToolkit):
    """Ostris AI-Toolkit for Flux and Stable Diffusion training.

    Best for: Flux LoRA training, SDXL fine-tuning, image generation models.
    """

    def info(self) -> ToolkitInfo:
        return ToolkitInfo(
            name="ai_toolkit",
            display_name="AI-Toolkit",
            description=(
                "Ostris AI-Toolkit for Flux and Stable Diffusion training. "
                "LoRA, full fine-tune, and DreamBooth for image generation."
            ),
            url="https://github.com/ostris/ai-toolkit",
            pip_package="ai-toolkit",
            supported_categories=[
                ModelCategory.VISION_GENERATION,
            ],
            supported_modes=[
                ToolkitCapability.FINE_TUNE,
                ToolkitCapability.LORA,
            ],
            min_vram_gb=12,
        )

    def validate_environment(self) -> list[str]:
        missing: list[str] = []
        try:
            import torch as _torch

            if not _torch.cuda.is_available():
                missing.append("CUDA (ai-toolkit requires NVIDIA GPU)")
        except ImportError:
            missing.append("torch")
        return missing

    # ── Project scaffolding ───────────────────────────────────

    def setup_project(self, project_dir: Path, spec: dict[str, Any]) -> None:
        configs_dir = project_dir / "configs"
        configs_dir.mkdir(parents=True, exist_ok=True)
        scripts_dir = project_dir / "scripts"
        scripts_dir.mkdir(parents=True, exist_ok=True)

        config = self.prepare_config(spec)
        (configs_dir / "training_config.json").write_text(json.dumps(config, indent=2))

        script = (
            "#!/usr/bin/env bash\n"
            "# Auto-generated by IMO — AI-Toolkit\n"
            "set -euo pipefail\n\n"
            "python run.py \\\n"
            '  --config "$(dirname "$0")/../configs/training_config.json"\n'
        )
        (scripts_dir / "train.sh").write_text(script)

    def prepare_config(self, spec: dict[str, Any]) -> dict[str, Any]:
        config: dict[str, Any] = {
            "model": spec.get("base_model", "black-forest-labs/FLUX.1-dev"),
            "output_dir": "./checkpoints",
            "resolution": spec.get("resolution", 1024),
            "train_batch_size": spec.get("batch_size", 1),
            "learning_rate": spec.get("learning_rate", 1e-4),
            "max_train_steps": spec.get("max_steps", 3000),
            "gradient_accumulation_steps": spec.get("gradient_accumulation_steps", 1),
            "mixed_precision": "bf16",
            "network_dim": spec.get("lora_r", 16),
            "network_alpha": spec.get("lora_alpha", 16),
        }
        return config

    def get_train_command(self, project_dir: Path) -> list[str]:
        return ["bash", str(project_dir / "scripts" / "train.sh")]

    # ── Model lifecycle ───────────────────────────────────────

    def load_model(self, spec: dict[str, Any]) -> nn.Module:
        from diffusers import UNet2DConditionModel

        base_model = spec.get("base_model", "black-forest-labs/FLUX.1-dev")

        unet = UNet2DConditionModel.from_pretrained(
            base_model, subfolder="unet", torch_dtype=torch.bfloat16
        )

        mode = spec.get("training_mode", "lora")
        if mode == "lora":
            from peft import LoraConfig, get_peft_model

            lora_config = LoraConfig(
                r=spec.get("lora_r", 16),
                lora_alpha=spec.get("lora_alpha", 16),
                target_modules=["to_q", "to_k", "to_v", "to_out.0"],
            )
            unet = get_peft_model(unet, lora_config)

        return unet

    def prepare_dataset(
        self, spec: dict[str, Any], split: str = "train"
    ) -> Any:
        from datasets import load_dataset

        dataset_path = spec.get("dataset_path", spec.get("dataset", ""))
        return load_dataset(dataset_path, split=split)

    def compute_loss(
        self,
        model: nn.Module,
        batch: dict[str, torch.Tensor],
    ) -> torch.Tensor:
        """Denoising diffusion loss for image generation."""
        latents = batch["latents"]
        noise = torch.randn_like(latents)
        num_steps = batch.get("num_diffusion_steps", torch.tensor(1000)).item()
        timesteps = torch.randint(0, int(num_steps), (latents.shape[0],), device=latents.device)

        alpha = 1.0 - timesteps.float() / int(num_steps)
        alpha = alpha.view(-1, 1, 1, 1)
        noisy_latents = alpha * latents + (1.0 - alpha) * noise

        encoder_hidden_states = batch.get("encoder_hidden_states")

        noise_pred = model(
            noisy_latents, timesteps, encoder_hidden_states=encoder_hidden_states
        ).sample

        return torch.nn.functional.mse_loss(noise_pred, noise)

    def create_optimizer(
        self, model: nn.Module, spec: dict[str, Any]
    ) -> tuple[torch.optim.Optimizer, torch.optim.lr_scheduler.LRScheduler | None]:
        lr = spec.get("learning_rate", 1e-4)
        optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-2)
        return optimizer, None
