"""Axolotl — config-driven LLM training (full, LoRA, RLHF)."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import torch
import torch.nn as nn

from imo.data.dataset_spec import ModelCategory
from imo.toolkits.base import ToolkitCapability, ToolkitInfo, TrainingToolkit


class AxolotlAdapter(TrainingToolkit):
    """Axolotl toolkit for config-driven LLM training.

    Best for: users who want a YAML-driven workflow with built-in support
    for chat templates, RLHF, DPO, and multi-dataset mixing.
    """

    def info(self) -> ToolkitInfo:
        return ToolkitInfo(
            name="axolotl",
            display_name="Axolotl",
            description=(
                "Config-driven LLM training. Supports full fine-tune, LoRA, QLoRA, "
                "DPO, RLHF. Wraps HF Trainer with rich YAML configuration."
            ),
            url="https://github.com/OpenAccess-AI-Collective/axolotl",
            pip_package="axolotl",
            supported_categories=[
                ModelCategory.LLM,
                ModelCategory.LLM_CHAT,
                ModelCategory.LLM_CODE,
                ModelCategory.MULTIMODAL_VLM,
            ],
            supported_modes=[
                ToolkitCapability.FROM_SCRATCH,
                ToolkitCapability.FINE_TUNE,
                ToolkitCapability.LORA,
                ToolkitCapability.QLORA,
                ToolkitCapability.CONTINUAL_PRETRAIN,
            ],
            min_vram_gb=8,
            extra_dependencies=["peft", "deepspeed"],
        )

    def validate_environment(self) -> list[str]:
        missing: list[str] = []
        try:
            import axolotl  # noqa: F401
        except ImportError:
            missing.append("axolotl")
        return missing

    # ── Project scaffolding ───────────────────────────────────

    def setup_project(self, project_dir: Path, spec: dict[str, Any]) -> None:
        configs_dir = project_dir / "configs"
        configs_dir.mkdir(parents=True, exist_ok=True)
        scripts_dir = project_dir / "scripts"
        scripts_dir.mkdir(parents=True, exist_ok=True)

        config = self.prepare_config(spec)
        config_path = configs_dir / "axolotl_config.json"
        config_path.write_text(json.dumps(config, indent=2))

        script = (
            "#!/usr/bin/env bash\n"
            "# Auto-generated by IMO — Axolotl\n"
            "set -euo pipefail\n\n"
            'CONFIG_DIR="$(dirname "$0")/../configs"\n'
            "axolotl train \"$CONFIG_DIR/axolotl_config.json\"\n"
        )
        (scripts_dir / "train.sh").write_text(script)

    def prepare_config(self, spec: dict[str, Any]) -> dict[str, Any]:
        mode = spec.get("training_mode", "full_fine_tune")
        config: dict[str, Any] = {
            "base_model": spec.get("base_model", ""),
            "model_type": "AutoModelForCausalLM",
            "output_dir": "./checkpoints",
            "sequence_len": spec.get("max_seq_length", 4096),
            "micro_batch_size": spec.get("batch_size", 4),
            "gradient_accumulation_steps": spec.get("gradient_accumulation_steps", 4),
            "learning_rate": spec.get("learning_rate", 1e-5),
            "num_epochs": spec.get("epochs", 3),
            "warmup_steps": spec.get("warmup_steps", 100),
            "weight_decay": spec.get("weight_decay", 0.01),
            "bf16": True,
            "flash_attention": True,
        }

        if mode in ("lora", "qlora"):
            config["adapter"] = "lora" if mode == "lora" else "qlora"
            config["lora_r"] = spec.get("lora_r", 32)
            config["lora_alpha"] = spec.get("lora_alpha", 16)
            config["lora_dropout"] = spec.get("lora_dropout", 0.05)

        return config

    def get_train_command(self, project_dir: Path) -> list[str]:
        return ["bash", str(project_dir / "scripts" / "train.sh")]

    # ── Model lifecycle ───────────────────────────────────────

    def load_model(self, spec: dict[str, Any]) -> nn.Module:
        from transformers import AutoModelForCausalLM

        base_model = spec.get("base_model", "")
        mode = spec.get("training_mode", "full_fine_tune")

        model = AutoModelForCausalLM.from_pretrained(
            base_model, torch_dtype=torch.bfloat16
        )

        if mode in ("lora", "qlora"):
            from peft import LoraConfig, get_peft_model

            lora_config = LoraConfig(
                r=spec.get("lora_r", 32),
                lora_alpha=spec.get("lora_alpha", 16),
                lora_dropout=spec.get("lora_dropout", 0.05),
                target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
            )
            model = get_peft_model(model, lora_config)

        return model

    def prepare_dataset(
        self, spec: dict[str, Any], split: str = "train"
    ) -> Any:
        from datasets import load_dataset

        dataset_path = spec.get("dataset_path", spec.get("dataset", ""))
        return load_dataset(dataset_path, split=split)

    def compute_loss(
        self,
        model: nn.Module,
        batch: dict[str, torch.Tensor],
    ) -> torch.Tensor:
        outputs = model(**batch)
        if hasattr(outputs, "loss") and outputs.loss is not None:
            return outputs.loss
        raise ValueError(
            "Model did not return loss. Ensure 'labels' is in the batch."
        )

    def create_optimizer(
        self, model: nn.Module, spec: dict[str, Any]
    ) -> tuple[torch.optim.Optimizer, torch.optim.lr_scheduler.LRScheduler | None]:
        lr = spec.get("learning_rate", 1e-5)
        wd = spec.get("weight_decay", 0.01)
        optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=wd)
        return optimizer, None
