"""Diffusers + Accelerate — universal diffusion model training."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import torch
import torch.nn as nn

from imo.data.dataset_spec import ModelCategory
from imo.toolkits.base import ToolkitCapability, ToolkitInfo, TrainingToolkit


class DiffusersAdapter(TrainingToolkit):
    """HuggingFace Diffusers toolkit for diffusion model training.

    Best for: general diffusion model training (SD, SDXL, Flux, audio/video
    diffusion). Supports full fine-tune, LoRA, DreamBooth.
    """

    def info(self) -> ToolkitInfo:
        return ToolkitInfo(
            name="diffusers",
            display_name="Diffusers",
            description=(
                "HuggingFace Diffusers with Accelerate. Universal diffusion model "
                "training: Stable Diffusion, SDXL, Flux, audio and video generation."
            ),
            url="https://github.com/huggingface/diffusers",
            pip_package="diffusers[torch]",
            supported_categories=[
                ModelCategory.VISION_GENERATION,
                ModelCategory.VIDEO_GENERATION,
                ModelCategory.AUDIO_SOUND_GENERATION,
                ModelCategory.AUDIO_TEXT_TO_SPEECH,
            ],
            supported_modes=[
                ToolkitCapability.FROM_SCRATCH,
                ToolkitCapability.FINE_TUNE,
                ToolkitCapability.LORA,
                ToolkitCapability.CONTINUAL_PRETRAIN,
            ],
            min_vram_gb=8,
            extra_dependencies=["accelerate", "peft"],
        )

    def validate_environment(self) -> list[str]:
        missing: list[str] = []
        try:
            import diffusers  # noqa: F401
        except ImportError:
            missing.append("diffusers")
        try:
            import accelerate  # noqa: F401
        except ImportError:
            missing.append("accelerate")
        return missing

    # ── Project scaffolding ───────────────────────────────────

    def setup_project(self, project_dir: Path, spec: dict[str, Any]) -> None:
        configs_dir = project_dir / "configs"
        configs_dir.mkdir(parents=True, exist_ok=True)
        scripts_dir = project_dir / "scripts"
        scripts_dir.mkdir(parents=True, exist_ok=True)

        config = self.prepare_config(spec)
        (configs_dir / "training_config.json").write_text(json.dumps(config, indent=2))

        script = (
            "#!/usr/bin/env bash\n"
            "# Auto-generated by IMO — Diffusers\n"
            "set -euo pipefail\n\n"
            "accelerate launch \\\n"
            "  train_diffusion.py \\\n"
            '  --config "$(dirname "$0")/../configs/training_config.json"\n'
        )
        (scripts_dir / "train.sh").write_text(script)

    def prepare_config(self, spec: dict[str, Any]) -> dict[str, Any]:
        mode = spec.get("training_mode", "full_fine_tune")
        config: dict[str, Any] = {
            "pretrained_model_name_or_path": spec.get("base_model", ""),
            "output_dir": "./checkpoints",
            "resolution": spec.get("resolution", 512),
            "train_batch_size": spec.get("batch_size", 4),
            "learning_rate": spec.get("learning_rate", 1e-4),
            "max_train_steps": spec.get("max_steps", 10000),
            "gradient_accumulation_steps": spec.get("gradient_accumulation_steps", 1),
            "mixed_precision": "fp16",
            "num_diffusion_steps": spec.get("num_diffusion_steps", 1000),
            "noise_schedule": spec.get("noise_schedule", "cosine"),
            "prediction_type": spec.get("prediction_type", "epsilon"),
        }
        if mode == "lora":
            config["use_lora"] = True
            config["lora_r"] = spec.get("lora_r", 4)
        return config

    def get_train_command(self, project_dir: Path) -> list[str]:
        return ["bash", str(project_dir / "scripts" / "train.sh")]

    # ── Model lifecycle ───────────────────────────────────────

    def load_model(self, spec: dict[str, Any]) -> nn.Module:
        from diffusers import UNet2DConditionModel

        base_model = spec.get("base_model", "")
        mode = spec.get("training_mode", "full_fine_tune")

        unet = UNet2DConditionModel.from_pretrained(
            base_model, subfolder="unet", torch_dtype=torch.float16
        )

        if mode == "lora":
            from peft import LoraConfig, get_peft_model

            lora_config = LoraConfig(
                r=spec.get("lora_r", 4),
                lora_alpha=spec.get("lora_alpha", 4),
                target_modules=["to_q", "to_k", "to_v", "to_out.0"],
            )
            unet = get_peft_model(unet, lora_config)

        return unet

    def prepare_dataset(
        self, spec: dict[str, Any], split: str = "train"
    ) -> Any:
        from datasets import load_dataset

        dataset_path = spec.get("dataset_path", spec.get("dataset", ""))
        return load_dataset(dataset_path, split=split)

    def compute_loss(
        self,
        model: nn.Module,
        batch: dict[str, torch.Tensor],
    ) -> torch.Tensor:
        """Denoising diffusion loss: predict noise from noisy input."""
        latents = batch["latents"]
        noise = torch.randn_like(latents)
        num_steps = batch.get("num_diffusion_steps", torch.tensor(1000)).item()
        timesteps = torch.randint(0, int(num_steps), (latents.shape[0],), device=latents.device)

        # Simple linear noise schedule
        alpha = 1.0 - timesteps.float() / int(num_steps)
        alpha = alpha.view(-1, 1, 1, 1)
        noisy_latents = alpha * latents + (1.0 - alpha) * noise

        encoder_hidden_states = batch.get("encoder_hidden_states")

        noise_pred = model(
            noisy_latents, timesteps, encoder_hidden_states=encoder_hidden_states
        ).sample

        return torch.nn.functional.mse_loss(noise_pred, noise)

    def create_optimizer(
        self, model: nn.Module, spec: dict[str, Any]
    ) -> tuple[torch.optim.Optimizer, torch.optim.lr_scheduler.LRScheduler | None]:
        lr = spec.get("learning_rate", 1e-4)
        optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-2)
        return optimizer, None
