"""HuggingFace Trainer + DeepSpeed/FSDP — the universal default toolkit."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import torch
import torch.nn as nn

from imo.data.dataset_spec import ModelCategory
from imo.toolkits.base import ToolkitCapability, ToolkitInfo, TrainingToolkit

_ALL_LANGUAGE_CATEGORIES = [
    ModelCategory.LLM,
    ModelCategory.LLM_CHAT,
    ModelCategory.LLM_CODE,
    ModelCategory.EMBEDDING_TEXT,
    ModelCategory.EMBEDDING_MULTIMODAL,
    ModelCategory.MULTIMODAL_VLM,
    ModelCategory.MULTIMODAL_AUDIO_VLM,
    ModelCategory.MULTIMODAL_VIDEO_VLM,
    ModelCategory.VISION_CLASSIFICATION,
    ModelCategory.AUDIO_SPEECH_RECOGNITION,
    ModelCategory.AUDIO_CLASSIFICATION,
    ModelCategory.TIME_SERIES_FORECASTING,
    ModelCategory.TIME_SERIES_CLASSIFICATION,
    ModelCategory.RECOMMENDATION,
]


class HFTrainerAdapter(TrainingToolkit):
    """Default toolkit using HuggingFace Transformers Trainer.

    Supports full fine-tuning, LoRA (via PEFT), from-scratch pretraining,
    continual pretraining, and distillation. Works with DeepSpeed ZeRO
    and PyTorch FSDP for multi-GPU.
    """

    def info(self) -> ToolkitInfo:
        return ToolkitInfo(
            name="hf_trainer",
            display_name="HF Trainer (Default)",
            description=(
                "HuggingFace Transformers Trainer with DeepSpeed/FSDP support. "
                "Universal full fine-tuning and pretraining for most model types."
            ),
            url="https://github.com/huggingface/transformers",
            pip_package="transformers[torch]",
            supported_categories=_ALL_LANGUAGE_CATEGORIES,
            supported_modes=[
                ToolkitCapability.FROM_SCRATCH,
                ToolkitCapability.FINE_TUNE,
                ToolkitCapability.LORA,
                ToolkitCapability.QLORA,
                ToolkitCapability.CONTINUAL_PRETRAIN,
                ToolkitCapability.DISTILLATION,
            ],
            min_vram_gb=8,
            extra_dependencies=["accelerate", "peft", "deepspeed"],
        )

    def validate_environment(self) -> list[str]:
        missing: list[str] = []
        try:
            import transformers  # noqa: F401
        except ImportError:
            missing.append("transformers")
        try:
            import accelerate  # noqa: F401
        except ImportError:
            missing.append("accelerate")
        try:
            import peft  # noqa: F401
        except ImportError:
            missing.append("peft (needed for LoRA/QLoRA)")
        return missing

    # ── Project scaffolding ───────────────────────────────────

    def setup_project(self, project_dir: Path, spec: dict[str, Any]) -> None:
        configs_dir = project_dir / "configs"
        configs_dir.mkdir(parents=True, exist_ok=True)
        scripts_dir = project_dir / "scripts"
        scripts_dir.mkdir(parents=True, exist_ok=True)

        config = self.prepare_config(spec)
        config_path = configs_dir / "training_config.json"
        config_path.write_text(json.dumps(config, indent=2))

        script = (
            "#!/usr/bin/env bash\n"
            "# Auto-generated by IMO — HF Trainer\n"
            "set -euo pipefail\n\n"
            'CONFIG_DIR="$(dirname "$0")/../configs"\n\n'
            "accelerate launch \\\n"
            "  --config_file \"$CONFIG_DIR/accelerate_config.yaml\" \\\n"
            "  -m imo.toolkits.builtin.hf_trainer_entry \\\n"
            "  --config \"$CONFIG_DIR/training_config.json\"\n"
        )
        script_path = scripts_dir / "train.sh"
        script_path.write_text(script)

    def prepare_config(self, spec: dict[str, Any]) -> dict[str, Any]:
        mode = spec.get("training_mode", "full_fine_tune")
        config: dict[str, Any] = {
            "model_name_or_path": spec.get("base_model", ""),
            "output_dir": "./checkpoints",
            "per_device_train_batch_size": spec.get("batch_size", 8),
            "learning_rate": spec.get("learning_rate", 1e-4),
            "num_train_epochs": spec.get("epochs", 3),
            "max_steps": spec.get("max_steps", -1),
            "warmup_steps": spec.get("warmup_steps", 100),
            "weight_decay": spec.get("weight_decay", 0.01),
            "logging_steps": 10,
            "save_steps": 500,
            "fp16": True,
            "gradient_accumulation_steps": spec.get("gradient_accumulation_steps", 1),
        }

        if mode in ("lora", "qlora"):
            config["use_peft"] = True
            config["lora_r"] = spec.get("lora_r", 16)
            config["lora_alpha"] = spec.get("lora_alpha", 32)
            config["lora_dropout"] = spec.get("lora_dropout", 0.05)
            if mode == "qlora":
                config["load_in_4bit"] = True

        if mode == "distillation":
            config["teacher_model"] = spec.get("teacher_model", "")

        return config

    def get_train_command(self, project_dir: Path) -> list[str]:
        return ["bash", str(project_dir / "scripts" / "train.sh")]

    # ── Model lifecycle ───────────────────────────────────────

    def load_model(self, spec: dict[str, Any]) -> nn.Module:
        from transformers import AutoConfig, AutoModelForCausalLM

        base_model = spec.get("base_model", "")
        mode = spec.get("training_mode", "full_fine_tune")

        if mode == "from_scratch":
            config = AutoConfig.from_pretrained(base_model)
            model = AutoModelForCausalLM.from_config(config)
        elif mode == "qlora":
            from transformers import BitsAndBytesConfig

            bnb_config = BitsAndBytesConfig(
                load_in_4bit=True,
                bnb_4bit_quant_type="nf4",
                bnb_4bit_compute_dtype=torch.bfloat16,
            )
            model = AutoModelForCausalLM.from_pretrained(
                base_model, quantization_config=bnb_config
            )
        else:
            model = AutoModelForCausalLM.from_pretrained(
                base_model, torch_dtype=torch.bfloat16
            )

        if mode in ("lora", "qlora"):
            from peft import LoraConfig, get_peft_model

            lora_config = LoraConfig(
                r=spec.get("lora_r", 16),
                lora_alpha=spec.get("lora_alpha", 32),
                lora_dropout=spec.get("lora_dropout", 0.05),
                target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
            )
            model = get_peft_model(model, lora_config)

        return model

    def prepare_dataset(
        self, spec: dict[str, Any], split: str = "train"
    ) -> Any:
        from datasets import load_dataset

        dataset_path = spec.get("dataset_path", spec.get("dataset", ""))
        return load_dataset(dataset_path, split=split)

    def compute_loss(
        self,
        model: nn.Module,
        batch: dict[str, torch.Tensor],
    ) -> torch.Tensor:
        outputs = model(**batch)
        if hasattr(outputs, "loss") and outputs.loss is not None:
            return outputs.loss
        raise ValueError(
            "Model did not return loss. Ensure 'labels' is in the batch."
        )

    def create_optimizer(
        self, model: nn.Module, spec: dict[str, Any]
    ) -> tuple[torch.optim.Optimizer, torch.optim.lr_scheduler.LRScheduler | None]:
        lr = spec.get("learning_rate", 1e-4)
        wd = spec.get("weight_decay", 0.01)
        warmup = spec.get("warmup_steps", 100)
        max_steps = spec.get("max_steps", 100000)

        optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=wd)

        from torch.optim.lr_scheduler import CosineAnnealingLR, LinearLR, SequentialLR

        warmup_scheduler = LinearLR(optimizer, start_factor=0.1, total_iters=warmup)
        decay_scheduler = CosineAnnealingLR(optimizer, T_max=max_steps - warmup)
        scheduler = SequentialLR(
            optimizer, schedulers=[warmup_scheduler, decay_scheduler], milestones=[warmup]
        )
        return optimizer, scheduler

    def post_training(self, model: nn.Module, project_dir: Path) -> None:
        try:
            from peft import PeftModel

            if isinstance(model, PeftModel):
                merged = model.merge_and_unload()
                merged.save_pretrained(project_dir / "merged_model")
        except ImportError:
            pass
