"""Musubi-Tuner — Wan2.1 video model fine-tuning."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import torch
import torch.nn as nn

from imo.data.dataset_spec import ModelCategory
from imo.toolkits.base import ToolkitCapability, ToolkitInfo, TrainingToolkit


class MusubiAdapter(TrainingToolkit):
    """Musubi-Tuner for Wan2.1 video generation model fine-tuning.

    Best for: Wan2.1 video model LoRA training and full fine-tuning.
    """

    def info(self) -> ToolkitInfo:
        return ToolkitInfo(
            name="musubi",
            display_name="Musubi-Tuner",
            description=(
                "Fine-tuning toolkit for Wan2.1 video generation models. "
                "Supports LoRA and full fine-tuning with frame-level control."
            ),
            url="https://github.com/kohya-ss/musubi-tuner",
            pip_package="musubi-tuner",
            supported_categories=[
                ModelCategory.VIDEO_GENERATION,
            ],
            supported_modes=[
                ToolkitCapability.FINE_TUNE,
                ToolkitCapability.LORA,
            ],
            min_vram_gb=12,
        )

    def validate_environment(self) -> list[str]:
        missing: list[str] = []
        try:
            import torch as _torch

            if not _torch.cuda.is_available():
                missing.append("CUDA (musubi-tuner requires NVIDIA GPU)")
        except ImportError:
            missing.append("torch")
        return missing

    # ── Project scaffolding ───────────────────────────────────

    def setup_project(self, project_dir: Path, spec: dict[str, Any]) -> None:
        configs_dir = project_dir / "configs"
        configs_dir.mkdir(parents=True, exist_ok=True)
        scripts_dir = project_dir / "scripts"
        scripts_dir.mkdir(parents=True, exist_ok=True)

        config = self.prepare_config(spec)
        (configs_dir / "training_config.json").write_text(json.dumps(config, indent=2))

        script = (
            "#!/usr/bin/env bash\n"
            "# Auto-generated by IMO — Musubi-Tuner\n"
            "set -euo pipefail\n\n"
            "python wan_train_network.py \\\n"
            '  --config "$(dirname "$0")/../configs/training_config.json"\n'
        )
        (scripts_dir / "train.sh").write_text(script)

    def prepare_config(self, spec: dict[str, Any]) -> dict[str, Any]:
        config: dict[str, Any] = {
            "pretrained_model_name_or_path": spec.get("base_model", "Wan-AI/Wan2.1-T2V-14B"),
            "output_dir": "./checkpoints",
            "resolution": spec.get("resolution", "832x480"),
            "video_length": spec.get("video_length", 81),
            "train_batch_size": spec.get("batch_size", 1),
            "learning_rate": spec.get("learning_rate", 1e-4),
            "max_train_steps": spec.get("max_steps", 1000),
            "gradient_accumulation_steps": spec.get("gradient_accumulation_steps", 1),
            "mixed_precision": "bf16",
            "network_dim": spec.get("lora_r", 32),
            "network_alpha": spec.get("lora_alpha", 16),
        }
        return config

    def get_train_command(self, project_dir: Path) -> list[str]:
        return ["bash", str(project_dir / "scripts" / "train.sh")]

    # ── Model lifecycle ───────────────────────────────────────

    def load_model(self, spec: dict[str, Any]) -> nn.Module:
        from diffusers import UNet3DConditionModel

        base_model = spec.get("base_model", "Wan-AI/Wan2.1-T2V-14B")

        unet = UNet3DConditionModel.from_pretrained(
            base_model, subfolder="unet", torch_dtype=torch.bfloat16
        )
        return unet

    def prepare_dataset(
        self, spec: dict[str, Any], split: str = "train"
    ) -> Any:
        from datasets import load_dataset

        dataset_path = spec.get("dataset_path", spec.get("dataset", ""))
        return load_dataset(dataset_path, split=split)

    def compute_loss(
        self,
        model: nn.Module,
        batch: dict[str, torch.Tensor],
    ) -> torch.Tensor:
        """Video diffusion denoising loss."""
        latents = batch["latents"]
        noise = torch.randn_like(latents)
        num_steps = batch.get("num_diffusion_steps", torch.tensor(1000)).item()
        timesteps = torch.randint(0, int(num_steps), (latents.shape[0],), device=latents.device)

        alpha = 1.0 - timesteps.float() / int(num_steps)
        alpha = alpha.view(-1, 1, 1, 1, 1)  # 5D for video: B, C, T, H, W
        noisy_latents = alpha * latents + (1.0 - alpha) * noise

        encoder_hidden_states = batch.get("encoder_hidden_states")

        noise_pred = model(
            noisy_latents, timesteps, encoder_hidden_states=encoder_hidden_states
        ).sample

        return torch.nn.functional.mse_loss(noise_pred, noise)

    def create_optimizer(
        self, model: nn.Module, spec: dict[str, Any]
    ) -> tuple[torch.optim.Optimizer, torch.optim.lr_scheduler.LRScheduler | None]:
        lr = spec.get("learning_rate", 1e-4)
        optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-2)
        return optimizer, None
