"""Unsloth — accelerated LoRA/QLoRA fine-tuning for LLMs."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import torch
import torch.nn as nn

from imo.data.dataset_spec import ModelCategory
from imo.toolkits.base import ToolkitCapability, ToolkitInfo, TrainingToolkit


class UnslothAdapter(TrainingToolkit):
    """Unsloth toolkit for 2-5x faster LoRA/QLoRA fine-tuning.

    Best for: LLM LoRA/QLoRA on single GPU with limited VRAM.
    """

    def info(self) -> ToolkitInfo:
        return ToolkitInfo(
            name="unsloth",
            display_name="Unsloth",
            description=(
                "2-5x faster LoRA/QLoRA fine-tuning for LLMs. "
                "Optimized kernels, 70% less memory. Single-GPU friendly."
            ),
            url="https://github.com/unslothai/unsloth",
            pip_package="unsloth",
            supported_categories=[
                ModelCategory.LLM,
                ModelCategory.LLM_CHAT,
                ModelCategory.LLM_CODE,
                ModelCategory.MULTIMODAL_VLM,
            ],
            supported_modes=[
                ToolkitCapability.LORA,
                ToolkitCapability.QLORA,
                ToolkitCapability.FINE_TUNE,
            ],
            min_vram_gb=6,
        )

    def validate_environment(self) -> list[str]:
        missing: list[str] = []
        try:
            import unsloth  # noqa: F401
        except ImportError:
            missing.append("unsloth")
        try:
            import torch as _torch

            if not _torch.cuda.is_available():
                missing.append("CUDA (unsloth requires NVIDIA GPU)")
        except ImportError:
            missing.append("torch")
        return missing

    # ── Project scaffolding ───────────────────────────────────

    def setup_project(self, project_dir: Path, spec: dict[str, Any]) -> None:
        configs_dir = project_dir / "configs"
        configs_dir.mkdir(parents=True, exist_ok=True)
        scripts_dir = project_dir / "scripts"
        scripts_dir.mkdir(parents=True, exist_ok=True)

        config = self.prepare_config(spec)
        (configs_dir / "training_config.json").write_text(json.dumps(config, indent=2))

        script = (
            "#!/usr/bin/env bash\n"
            "# Auto-generated by IMO — Unsloth\n"
            "set -euo pipefail\n\n"
            "python -m imo.toolkits.builtin.unsloth_entry \\\n"
            '  --config "$(dirname "$0")/../configs/training_config.json"\n'
        )
        (scripts_dir / "train.sh").write_text(script)

    def prepare_config(self, spec: dict[str, Any]) -> dict[str, Any]:
        mode = spec.get("training_mode", "lora")
        config: dict[str, Any] = {
            "model_name": spec.get("base_model", "unsloth/llama-3-8b-bnb-4bit"),
            "max_seq_length": spec.get("max_seq_length", 2048),
            "per_device_train_batch_size": spec.get("batch_size", 4),
            "learning_rate": spec.get("learning_rate", 2e-4),
            "num_train_epochs": spec.get("epochs", 1),
            "max_steps": spec.get("max_steps", -1),
            "warmup_steps": spec.get("warmup_steps", 10),
            "logging_steps": 10,
            "save_steps": 500,
            "output_dir": "./checkpoints",
            "lora_r": spec.get("lora_r", 16),
            "lora_alpha": spec.get("lora_alpha", 16),
            "lora_dropout": spec.get("lora_dropout", 0.0),
            "target_modules": [
                "q_proj", "k_proj", "v_proj", "o_proj",
                "gate_proj", "up_proj", "down_proj",
            ],
        }
        if mode == "qlora":
            config["load_in_4bit"] = True
        return config

    def get_train_command(self, project_dir: Path) -> list[str]:
        return ["bash", str(project_dir / "scripts" / "train.sh")]

    # ── Model lifecycle ───────────────────────────────────────

    def load_model(self, spec: dict[str, Any]) -> nn.Module:
        from unsloth import FastLanguageModel

        model_name = spec.get("base_model", "unsloth/llama-3-8b-bnb-4bit")
        max_seq_len = spec.get("max_seq_length", 2048)
        load_4bit = spec.get("training_mode", "lora") == "qlora"

        model, _tokenizer = FastLanguageModel.from_pretrained(
            model_name=model_name,
            max_seq_length=max_seq_len,
            load_in_4bit=load_4bit,
        )

        model = FastLanguageModel.get_peft_model(
            model,
            r=spec.get("lora_r", 16),
            lora_alpha=spec.get("lora_alpha", 16),
            lora_dropout=spec.get("lora_dropout", 0.0),
            target_modules=[
                "q_proj", "k_proj", "v_proj", "o_proj",
                "gate_proj", "up_proj", "down_proj",
            ],
        )
        return model

    def prepare_dataset(
        self, spec: dict[str, Any], split: str = "train"
    ) -> Any:
        from datasets import load_dataset

        dataset_path = spec.get("dataset_path", spec.get("dataset", ""))
        return load_dataset(dataset_path, split=split)

    def compute_loss(
        self,
        model: nn.Module,
        batch: dict[str, torch.Tensor],
    ) -> torch.Tensor:
        outputs = model(**batch)
        if hasattr(outputs, "loss") and outputs.loss is not None:
            return outputs.loss
        raise ValueError(
            "Model did not return loss. Ensure 'labels' is in the batch."
        )

    def create_optimizer(
        self, model: nn.Module, spec: dict[str, Any]
    ) -> tuple[torch.optim.Optimizer, torch.optim.lr_scheduler.LRScheduler | None]:
        lr = spec.get("learning_rate", 2e-4)
        optimizer = torch.optim.AdamW(model.parameters(), lr=lr)
        return optimizer, None

    def post_training(self, model: nn.Module, project_dir: Path) -> None:
        model.save_pretrained(project_dir / "lora_adapter")
